# Generated by Django 5.2 on 2025-06-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description0", models.TextField(blank=True)),
                ("description1", models.TextField(blank=True)),
                ("description2", models.TextField(blank=True)),
                ("description3", models.TextField(blank=True)),
            ],
        ),
    ]
