# Generated by Django 5.2 on 2025-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("la_qab", models.CharField(max_length=100)),
                ("username", models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
