# Generated by Django 5.2 on 2025-06-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot",
            old_name="bot_access",
            new_name="accesses",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="last_used",
        ),
    ]
