# Generated by Django 5.2 on 2025-06-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AI",
            fields=[
                (
                    "name",
                    models.CharField(
                        editable=False, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=120)),
                ("msgs", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to="account.user",
                    ),
                ),
                (
                    "descriptions",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.description",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by",
                        to="account.user",
                    ),
                ),
            ],
        ),
    ]
