# Generated by Django 5.2 on 2025-06-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai",
            name="model",
        ),
        migrations.AddField(
            model_name="ai",
            name="ai_models",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="ai",
            name="description0",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ai",
            name="description1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ai",
            name="description2",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ai",
            name="description3",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ai",
            name="msgs",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterModelTable(
            name="ai",
            table="ai_model",
        ),
    ]
