# Generated by Django 5.2 on 2025-06-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_20250603_1945"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai",
            name="ai_models",
        ),
    ]
