# Generated by Django 5.2 on 2025-06-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_20250604_1938"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai",
            name="key",
        ),
    ]
