# Generated by Django 5.2 on 2025-06-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin3Button",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "button_sort",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (132, "Info\nModels\nSettings"),
                            (213, "Models\nInfo\nSettings"),
                            (231, "Models\nSettings\nInfo"),
                            (321, "Info\nModels\nInfo"),
                            (312, "Info\nInfo\nModels"),
                        ]
                    ),
                ),
                ("buttons", models.TextField()),
            ],
        ),
    ]
